name: Changesets
description: A GitHub action to automate releases with Changesets
runs:
  using: "node12"
  main: "dist/index.js"
inputs:
  autoPublish:
    description: "A boolean value to enable auto publishing"
    required: false
    default: "false"
  dedupe:
    description: "A boolean value to enable auto deduplication"
    required: false
    default: "false"
  version:
    description: "The command to update version, edit CHANGELOG, read and delete changesets. Default to `yarn changeset version` if not provided"
    required: false
    default: "yarn changeset version"
  commit:
    description: |
      The commit message. Default to `Version Packages`
    required: false
    default: "Version Packages"
  title:
    description: The pull request title. Default to `Version Packages`
    required: false
    default: "Version Packages"
outputs:
  published:
    description: A boolean value to indicate whether a publishing is happened or not
  publishedPackages:
    description: >
      A JSON array to present the published packages. The format is `[{"name": "@xx/xx", "version": "1.2.0"}, {"name": "@xx/xy", "version": "0.8.9"}]`
branding:
  icon: "package"
  color: "blue"
